# Site settings
title: L-Cubed Blog
header-img: img/home-bg.jpg
email: xorxushengliu@sina.com
description: "L-Cubed Blog"
baseurl: ""
url: "http:lcubed.github.io"
#twitter_username: lcubed
github_username:  lcubed
#facebook_username:  lcubed

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
